### PR TITLE
Adding new attributes for specifying numeric setting bounds and numeric control UI type

### PR DESCRIPTION
**Pull request by fredjk-gh**
This is will be used for the upcoming Announcer plugin. Allows a setting to specify upper and lower bounds and a non-default increment in the numeric spinner control.

### CODE REVIEW

**Review by Xjph — CHANGES_REQUESTED** [review]
Really like having this attribute, but don't like always using `double` regardless of whatever type it's attached to. Would be much happier if it could be made to match types, either via overloads or generics (though I'm not sure there's a nice way to use generic types in an attribute).

**Comment by fredjk-gh** [comment]
As you've already discovered, generics aren't an option for attributes. To that end, I'm inclined to leave this as is because both options for underlying controls for this purpose (Slider and NumericUpDown) both use double for Minimum, Maximum and Increment (NumericUpDown only), and so customizing the type to anything but double will incur unnecessary casting and will make usage of this attribute increasingly messy.

Per our out-of-band discussion and eluded to above, I've added a Slider-based implementation for a numeric I'm adding a new parameter-less "tag" attribute named "SettingNumericUseSlider" for specifying usage of the Slider for a numeric setting vs. the default NumericUpDown. The same SettingNumericBounds attribute can be used interchangeably for specifying bounds for either underlying control.

WDYT?

**Comment by Xjph** [comment]
So part of my original thoughts with plugin settings was making a basic implementation of them as simple as possible for the plugin author. They could _decorate_ with attributes if necessary (like specifying the display name), but the basic functionality of just having the setting would be as simple as picking a type and getting its corresponding setting behaviour.

My plan for numeric values that required a bounded range, which I explained to you in said out-of-band conversation, was that a `float` setting use a slider in a 0...1 range, which the plugin author would expand via multiplication to the range they needed. The second time I mentioned it I directly asked if you had any issues with that idea. At no point did you indicate any problems or suggest an alternative.

To be completely clear, I'm not _married_ to my original idea, and am up for discussing alternatives, but the time to do that is _before_ I'm staring at a PR for a feature I wasn't expecting. I no longer feel like it's actually possible to properly weigh the options of each plan, since saying "no" to this one now means throwing out the work you've done. I probably would've gone ahead with it, I'm generally fairly agreeable, and the attribute is clearer in its intent than just creating a `float`, indeed the more I think about it the more I do agree this is the better solution, but I do _not_ like the opportunity to even have the conversation being dodged like this.

**Review by Xjph — APPROVED** [review]
Happy enough with these changes after some further thought, but in future _please_ discuss with me if you want to do something other than my original suggestions instead of just going ahead and creating a PR for something different.
If I had more free time this weekend and had started work in a different direction then something would had to have gotten thrown out.

**Pull request merged**
